# Generated by Django 3.2.16 on 2024-01-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='title',
            new_name='following',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='description',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='slug',
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='auth.user'),
            preserve_default=False,
        ),
    ]
